<h2>Creation d'un compte Client</h2>
<form class="generic-form" method="post" action="<?= $requestUrl?>/user.php">
 	<ul>
   <fieldset>
       <legend><i class="fa fa-user"></i>Identité et cordonnées</legend> <!-- Titre du fieldset --> 
       <li>
       <label for="FirstName">Nom </label>
       <input type="text" name="FirstName" id="FirstName" />
       </li>
       <li>
       <label for="LastName">Prenom </label>
       <input type="text" name="LastName" id="LastName" />
       </li>

       	<li>
	    <label for="date">Date de Naissance: </label>
			    <span>
				     <select name="day">

				     	<? for($j = 1; $j <=31 ;$j++):
				     		if($j == date('d')) :?>
				     		<option selected value='<?=$j?>'><?=$j?></option>
				     		<? else : ?>
				     			<option value='<?=$j?>'><?=$j?></option>
				     		<?endif;?> 
				     	<?endfor;?>  

				     </select>
				</span>
			 	<span>
		     	<select name="month">
		        	<? $months = ['01' =>'January','02'=>'February','03'=>'March','04'=>'April','05'=>'May',
		                        '06'=>'June','07'=>'July','08'=>'August','09'=>'September','10'=>'October',
		                         '11'=>'November','12'=>'December'];

		                        foreach ($months as $key => $value) :?>

		                        <option value="<?=$key?>"><?=$value?></option>
		                            
		                          <? endforeach ?>

		     </select> 
			</span>

			<span>
			     <select name="year">
			     	<? $datefin = date('Y');
			     	 for($year=1940; $year<=$datefin - 18; $year++): ?>
			     		<option value="<?=$year?>"><?=$year?></option>
			     	 <? endfor; ?>    
			     </select>
			</span>
    	</li>

    	<li>
       <label for="Address">Address</label>
       <textarea class="textarea" type="text" name="Address" id="Address"></textarea>
       </li>
       <li>
       <label for="City">Ville </label>
       <input type="text" name="City" id="City" />
       </li>
       <li>
       <label for="ZipCode">Code Postale </label>
       <input class="zip-code" type="text" name="ZipCode" id="ZipCode" />
       </li>
       <li>
        <label for="Country">Pays : </label>
       <input type="text" name="Country" id="Country" />
       </li>
       <li>
        <label for="Phone">Telephone : </label>
       <input class="phone" type="text" name="Phone" id="Phone" />
       </li>

   </fieldset>
 
   <fieldset>
       <legend><i class="fa fa-lock"></i>Information d'authentification</legend> <!-- Titre du fieldset -->
 
       <li>
	       <label for="Email"> mail </label>
	       <input type="email" name="Email" id="Email" />
       </li>
       <li>
       	  <label for="pass">Votre mot de passe :</label>
      	  <input type="password" name="pass" id="pass" />
       </li>
       <li>
       	<button class="button button-primary" type="submit" value="Envoyer" />Envoyer</button>
       	<button class="button button-cancel" type="reset" value="Annuler" />Annuler</button>
       </li>

         
   </fieldset>
   </ul>
</form>